CREATE DATABASE DBSALES
USE DBSALES

CREATE TABLE User_Role(
RoleId INT PRIMARY KEY IDENTITY(1, 1),
RoleName VARCHAR(50),
RecordDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Menu(
MenuId INT PRIMARY KEY IDENTITY(1, 1),
MenuName VARCHAR(50),
Icon VARCHAR(50),
MenuUrl VARCHAR(50)
);

CREATE TABLE RoleMenu(
RoleMenuId INT PRIMARY KEY IDENTITY(1, 1),
MenuId INT REFERENCES Menu(MenuId),
RoleId INT REFERENCES User_Role(RoleId)
);

CREATE TABLE App_User(
UserId INT PRIMARY KEY IDENTITY(1, 1),
CompleteName VARCHAR(100),
Email VARCHAR(40),
RoleId INT REFERENCES User_Role(RoleId),
Pass VARCHAR(40),
IsActive BIT DEFAULT 1,
RecordDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Category(
CategoryId INT PRIMARY KEY IDENTITY(1, 1),
CategoryName VARCHAR(50),
IsActive BIT DEFAULT 1,
RecordDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Product(
ProductId INT PRIMARY KEY IDENTITY(1, 1),
ProductName VARCHAR(100),
CategoryId INT REFERENCES Category(CategoryId),
Stock INT,
Price DECIMAL(10, 2),
IsActive BIT DEFAULT 1,
RecordDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE DocumentNumber(
DocumentNumberId INT PRIMARY KEY IDENTITY(1, 1),
Last_Number INT NOT NULL,
RecordDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Sale(
SaleId INT PRIMARY KEY IDENTITY(1, 1),
DocumentNumber VARCHAR(40),
PaymentType VARCHAR(50),
Total DECIMAL(10, 2),
RecordDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE SaleDetail(
SaleDetailId INT PRIMARY KEY IDENTITY(1, 1),
SaleId INT REFERENCES Sale(SaleId),
ProductId INT REFERENCES Product(ProductId),
Amount INT,
Price DECIMAL(10, 2),
Total DECIMAL(10, 2)
);